### ISSUE TITLE
data_updater.py によるデータ取得ができない

### ISSUE THREAD

**Issue by Meiryo7743** [Meiryo7743/covid-19-ichikawa#163]
## 詳細 / Details

 `data_updater.py` でデータが取得できない状態になっており，代わりにエラーページの何かが生成されている。

- [当該箇所の差分](https://github.com/Meiryo7743/covid-19-ichikawa/commit/12b3973ce3664fc7f722a9bf6d1595dec94d4cf5#diff-3a6eb0790f39ac87c94f3856b2dd2c5d110e6811602261a9a923d3bb23adc8b7)

## 期待される動作 / Expected behavior

- スプレッドシートの TSV データを利用するのではなく，Python 自身で完結する処理に変更すべき

## 再現方法 / Steps to reproduce

1. `data_updater.py` を実行する

**Comment by Meiryo7743** [comment]
元々，手動でデータ更新していた時の手順を当該の `data_updater.py` で再現することで，無理矢理自動化していました。

現行の `data_updater.py` は暫定的なものとし，ゆくゆくは Python 単体で完結する形に修正する予定でした。ところが，その改良版の試作中に事態が起こった……という流れになります。

## 現行の仕様

1. Google スプレッドシートにアクセスする
2. TSV 形式でダウンロードする
3. ダウンロードした TSV ファイルを YAML 形式に変換処理する
4. YAML ファイルとして保存する
5. TSV ファイルを削除する

## 改良版の仕様（仮）

1. 市川市のページから表を取得する
2. 表を CSV 形式に変換する
3. 各列のデータをリスト化し，書式を修正する
4. 修正したデータを再度 CSV 形式に変換する
5. JSON 形式に変換する
6. JSON ファイルとして出力する

### 手順 4 の書式の修正について

市川市が公開している表データは，手入力で更新していると推測されます。このため書式に統一性がなく，そのまま JSON に変換した状態では Hugo で表を自動生成できません。

そこで，JSON に変換する前に，一旦各データの体裁を機械処理可能な形式に整える作業を行う必要があります。以下の表は，その必要がある項目と修正後の形式等を示すものです。

| 対象項目 | 元データ例 | 修正 | 備考 |
| --- | --- | --- | --- |
| 市内 | `市内XXX例目` | `XXX` | 数字だけ抽出する |
| 県内 | `XXXX例目`<br>`船橋YYY例目` | `XXXX` | 県内何例目の数字のみ抽出する |
| 職業 | `会社員` | `会社員` | 不明・調査中表記を削除する |
| 推定感染経路 | `県内XXXX接触` | `県内XXXX` | 不明・調査中表記を削除する<br>リスト形式に変換する<br>「接触」表記を削る |
| 行動歴 | `自宅、医療機関` | `['自宅', '医療機関']` | 不明・調査中表記を削除する<br>リスト形式に変換する |
| 検査確定日 | `MM月DD日` | `YYYY-MM-DD` | 不明・調査中表記を削除する |
| 発症日 | `MM月DD日` | `YYYY-MM-DD` | 不明・調査中表記を削除する |

**Comment by evidnece** [comment]
YAMLの書き込み先をopenする際に、encoding='utf-8'を指定すれば実行できました。
56～62行目を以下のように変更しては如何でしょうか。

    # Convert TSV to YAML
    with open(FILE_YAML, 'w', encoding='utf-8') as f:
        yaml.dump(data, f, encoding='utf-8', allow_unicode=True)

    # Get the content of YAML
    with open(FILE_YAML, encoding='utf-8') as f:
        content = f.read()

**Comment by evidnece** [comment]
57行目と65行目のopenにencoding='utf-8'を追記すれば実行できました。
修正後の56行目以降を転記します。

    # Convert TSV to YAML
    with open(FILE_YAML, 'w', encoding='utf-8') as f:
        yaml.dump(data, f, encoding='utf-8', allow_unicode=True)

    # Get the content of YAML
    with open(FILE_YAML, encoding='utf-8') as f:
        content = f.read()

    # Replace some strings in order to be correct YAML format
    with open(FILE_YAML, 'w', encoding='utf-8') as f:
        content = re.sub(r"'(\[.+\]|\d+|)'", r'\1', content)
        f.write(content)

    # Delete TSV files
    os.remove(FILE_TSV)

**Comment by Meiryo7743** [comment]
@evidnece

検証・コード修正のご提示ありがとうございます。

当方も Windows 10 で実行したところ，同様の現象を確認しました。Github Actions の実行環境（Ubuntu）上では，特に発生していなかったのでスルーしていました……。

---

実を言うと，**いま直面している問題は，スプレッドシートからのダウンロードが正常に行われないこと**なんです。

取り急ぎで建てた issue ゆえに，説明不足なところがあって申し訳ないです。エラーの詳細について前項に追記しておきます。
